<?php
/**
 * The reading post type.
 *
 * @package HealthPress
 */

declare( strict_types = 1 );

namespace HealthPress\Storage;

/**
 * Registers `hp_reading`, the post type one measurement is stored as.
 *
 * Readings are private data: not public, not queryable, not in search. The
 * admin screen stays on so raw rows can be inspected while there is no custom
 * UI, but the core REST endpoint is off — exposing `/wp/v2/hp_reading` would
 * create a second write path straight to `wp_insert_post()` that never reaches
 * the validator.
 */
final class Post_Type {

	/**
	 * The post type name. Post type names are capped at 20 characters.
	 */
	public const SLUG = 'hp_reading';

	/**
	 * Registers the post type. Hooked to `init` at the default priority.
	 */
	public function register(): void {
		register_post_type(
			self::SLUG,
			array(
				'labels'              => array(
					'name'               => __( 'Readings', 'healthpress' ),
					'singular_name'      => __( 'Reading', 'healthpress' ),
					'menu_name'          => __( 'HealthPress', 'healthpress' ),
					'add_new_item'       => __( 'Add Reading', 'healthpress' ),
					'edit_item'          => __( 'Edit Reading', 'healthpress' ),
					'view_item'          => __( 'View Reading', 'healthpress' ),
					'search_items'       => __( 'Search Readings', 'healthpress' ),
					'not_found'          => __( 'No readings found.', 'healthpress' ),
					'not_found_in_trash' => __( 'No readings found in Trash.', 'healthpress' ),
					'all_items'          => __( 'All Readings', 'healthpress' ),
				),
				'public'              => false,
				'show_ui'             => true,
				'show_in_menu'        => true,
				'show_in_nav_menus'   => false,
				'publicly_queryable'  => false,
				'exclude_from_search' => true,
				'has_archive'         => false,
				'rewrite'             => false,
				'query_var'           => false,
				'menu_icon'           => 'dashicons-heart',
				'menu_position'       => 30,

				/*
				 * Off deliberately: healthpress/v1 is the only write path, so
				 * that every reading goes through Reading_Validator.
				 */
				'show_in_rest'        => false,

				/*
				 * Nothing about a reading is authored, so core renders none of
				 * its own fields and the Reading metabox supplies everything.
				 *
				 * The title is generated by the repository, the note is written
				 * to post_content from validated input, and `custom-fields` was
				 * never actually usable: `_hp_*` keys are protected meta, which
				 * `add_meta()` rejects before it even consults the auth_callback
				 * registered against them.
				 *
				 * `false`, not `array()`. WP_Post_Type::add_supports() treats an
				 * empty array as "unspecified" and falls through to the default
				 * title/editor/autosave set; only `false` means none.
				 */
				'supports'            => false,
				'map_meta_cap'        => true,
				'capability_type'     => 'post',
				'taxonomies'          => array( Taxonomy::SLUG ),
			)
		);
	}
}
