<?php
/**
 * Keeps non-readings out of the published set.
 *
 * @package HealthPress
 */

declare( strict_types = 1 );

namespace HealthPress\Storage;

/**
 * Stops a reading that was never written by the repository from publishing.
 *
 * Every real reading has its title generated by `Post_Reading_Repository`, so
 * an `hp_reading` being written with a blank title is by construction not a
 * reading — it is core's editor publishing an empty post, which is exactly how
 * a row with a metric term and no values used to appear.
 *
 * This is the barrier that makes "cannot produce a published reading" true,
 * rather than merely "cannot surface one". The read-time guard in `hydrate()`
 * handles rows that already exist; this one stops new ones.
 */
final class Publish_Guard {

	/**
	 * Statuses a titleless reading must not be written in.
	 *
	 * `future` is not an edge case, it is the same case arriving by a different
	 * route. `wp_insert_post()` rewrites `publish` to `future` whenever the date
	 * is at least a minute ahead (wp-includes/post.php:4709) — and it does so
	 * 176 lines *before* it applies `wp_insert_post_data`, so a guard that only
	 * inspects `publish` never sees the write at all.
	 *
	 * Leaving it would be worse than leaving a bad row, because cron promotes it
	 * later through `wp_publish_post()`, which is a bare `$wpdb->update` that
	 * touches no filter and gives nothing a second chance to object.
	 *
	 * Catching it here rather than at the transition also means the post never
	 * enters `future` at all, so `_future_post_hook()` never schedules the cron
	 * event in the first place.
	 */
	private const GUARDED = array( 'publish', 'future' );

	/**
	 * Registers the guard.
	 */
	public function register(): void {
		add_filter( 'wp_insert_post_data', array( $this, 'demote_titleless' ), 10, 1 );
	}

	/**
	 * Demotes a titleless reading out of the published set.
	 *
	 * `create()` inserts its placeholder as a draft and `save()` always supplies
	 * a generated title, so no legitimate write is affected. A reading cannot
	 * legitimately be future-dated either — `Reading_Validator` rejects that as
	 * `hp_future_date` — so demoting `future` costs nothing real.
	 *
	 * Note `wp_publish_post()` bypasses `wp_insert_post()` with a direct
	 * `$wpdb->update`, so it is not covered. That is precisely why `future` is
	 * guarded here: cron reaches `wp_publish_post()` through that status, and
	 * this is the last point at which anything can object.
	 *
	 * @param array<string, mixed> $data Slashed, sanitised post data about to be written.
	 *
	 * @return array<string, mixed>
	 */
	public function demote_titleless( array $data ): array {
		if ( Post_Type::SLUG !== ( $data['post_type'] ?? '' ) ) {
			return $data;
		}

		if ( ! in_array( $data['post_status'] ?? '', self::GUARDED, true ) ) {
			return $data;
		}

		if ( '' !== trim( (string) ( $data['post_title'] ?? '' ) ) ) {
			return $data;
		}

		$data['post_status'] = 'draft';

		return $data;
	}
}
